packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^4
  typescript: ^5.8.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.71.10
  "@trpc/client": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0

  # Misc
  zod: ^3.24.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
