services:
  postgres:
    image: postgres
    container_name: db-xpertzone
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecurepassword}
      POSTGRES_DB: xpertzone
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres

volumes:
  postgres-data:

  # docker exec -it db-xpertzone psql -U admin -d xpertzone
